### ISSUE TITLE
Running on Windows from an Ubuntu subsystem

### ISSUE THREAD

**Issue by moldovannorbert** [mbhall88/streamformatics#2]
I'm not sure if the environment or another issue causes this error:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle uwa_pipeline@1.0.0~prestart: uwa_pipeline@1.0.0
6 info lifecycle uwa_pipeline@1.0.0~start: uwa_pipeline@1.0.0
7 verbose lifecycle uwa_pipeline@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle uwa_pipeline@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/moldovannorbert/streamformatics/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle uwa_pipeline@1.0.0~start: CWD: /home/moldovannorbert/streamformatics
10 silly lifecycle uwa_pipeline@1.0.0~start: Args: [ '-c', 'node app.js' ]
11 silly lifecycle uwa_pipeline@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle uwa_pipeline@1.0.0~start: Failed to exec start script
13 verbose stack Error: uwa_pipeline@1.0.0 start: `node app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid uwa_pipeline@1.0.0
15 verbose cwd /home/moldovannorbert/streamformatics
16 verbose Linux 4.4.0-17134-Microsoft
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error uwa_pipeline@1.0.0 start: `node app.js`
22 error Exit status 1
23 error Failed at the uwa_pipeline@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

The server does start and I can add the path to the files, but after submitting there are 0 reads processed.

**Comment by mbhall88** [comment]
Could you please also add the details of the Ubuntu version you are using and also the node.js version.

**Comment by moldovannorbert** [comment]
Oh, sorry I forgot to add that.
Ubuntu 16.04.4
node.js 8.11.3-1nodesourc

**Comment by mbhall88** [comment]
Ok, so it has been a very long time since I have looked at this repository. I just had a quick play then and am also having problems trying to get the local server started.  
It has been ages since I looked at any webdev technologies and it is such a fast moving community. I believe there are a lot of out-of-date packages I am using.  
Realistically I would probably need/like to rewrite this service completely. However, I do not have a huge amount of time on my hands currently to tackle that as I am doing my PhD in a somewhat different area. I will leave this issue open and work away at trying to fix all the code in this repository when I get the chance. Very sorry I can't help at this moment.

**Comment by themouldinator** [comment]
@mbhall88 I've just hit the same issue as moldovannorbert, I was wondering if you'd found a fix of any kind? It would be really useful for my research!! Thanks for your contribution to the community, its greatly appreciated!

**Comment by mbhall88** [comment]
@themouldinator no I haven't sorry. As I mentioned in the above comment the whole thing effectively needs to be rewritten as a lot of versions/packages/tech is out of date. As this is not related to my current PhD project I don't have time to dedicate to doing this sorry.   
You are obviously very welcome to clone the repository and do so yourself though.

**Comment by themouldinator** [comment]
@mbhall88 ah shucks =/
I dont really have the knowhow to do that, my coding is basic shell scripting at the moment... but hey, I'll give it a go, whats the worst that could happen =P 
Thanks anyway, hope you have a great weekend =)
